export const nodes = [
  { id: 'soesje',      name: 'Soesje',        gen: 1, photo: null },
  { id: 'ginny',       name: 'Ginny',          gen: 1, photo: 'katten/ginny.jpg' },
  { id: 'safira',      name: 'Safira',         gen: 1, photo: 'katten/safira.jpg' },
  { id: 'ruby',        name: 'Ruby',           gen: 2, photo: 'katten/ruby.jpg' },
  { id: 'roosje',      name: 'Roosje',         gen: 2, photo: 'katten/roosje.jpg' },
  { id: 'midnight',    name: 'Midnight',       gen: 2, photo: 'katten/midnight.jpg' },
  { id: 'sparkle',     name: 'Sparkle',        gen: 2, photo: 'katten/sparkle.jpg' },
  { id: 'lieffie',     name: 'Lieffie',        gen: 2, photo: 'katten/lieffie.jpg' },
  { id: 'lily',        name: 'Lily',           gen: 2, photo: 'katten/lily.jpg' },
  { id: 'royke',       name: 'Royke',          gen: 2, photo: 'katten/royke.jpeg' },
  { id: 'speedy',      name: 'Speedy',         gen: 3, photo: 'katten/speedy.jpg' },
  { id: 'piraatje',    name: 'Piraatje',       gen: 3, photo: 'katten/piraatje.jpg' },
  { id: 'bloesempje',  name: 'Bloesempje',     gen: 3, photo: null },
  { id: 'schatje',     name: 'Schatje',        gen: 3, photo: 'katten/schatje.jpeg' },
  { id: 'lillifee',    name: 'Lillifee',       gen: 3, photo: 'katten/lillifee.jpeg' },
  { id: 'flip',        name: 'Flip',           gen: 4, photo: 'katten/flip.jpeg',          birth: '16 sep 2015' },
  { id: 'fjoepie',     name: 'Fjoepie',        gen: 4, photo: 'katten/fjoepie.jpeg',       birth: '16 sep 2015' },
  { id: 'spilly',      name: 'Spilly',         gen: 4, photo: 'katten/spilly.jpeg',        birth: '16 sep 2015' },
  { id: 'noodle',      name: 'Noodle',         gen: 4, photo: 'katten/noodle.jpg',         birth: '16 sep 2015' },
  { id: 'nibbit',      name: 'Nibbit',         gen: 4, photo: 'katten/nibbit.jpeg',        birth: '16 sep 2015' },
  { id: 'streepje',    name: 'Streepje',       gen: 4, photo: 'katten/streepje.jpeg',      birth: '3 okt 2015' },
  { id: 'ziva',        name: 'Ziva',           gen: 4, photo: 'katten/ziva.jpeg',          birth: '3 okt 2015' },
  { id: 'zara',        name: 'Zara',           gen: 4, photo: 'katten/zara.jpeg',          birth: '3 okt 2015' },
  { id: 'sunny',       name: 'Sunny',          gen: 4, photo: 'katten/sunny.jpeg',         birth: '3 okt 2015' },
  { id: 'sneeuwvlokje',name: 'Sneeuwvlokje',  gen: 4, photo: 'katten/sneeuwvlokje.jpeg',  birth: '3 okt 2015' },
  { id: 'oreo',        name: 'Oreo',           gen: 4, photo: 'katten/oreo.jpeg',          birth: '3 okt 2015' },
  { id: 'bambi',       name: 'Bambi',          gen: 4, photo: 'katten/bambi.jpeg',         birth: '28 sep 2015' },
  { id: 'shadow',      name: 'Shadow',         gen: 4, photo: 'katten/shadow.jpeg',        birth: '28 sep 2015' },
  { id: 'charlie',     name: 'Charlie',        gen: 4, photo: 'katten/charlie.jpeg',       birth: '28 sep 2015' },
  { id: 'noortje',     name: 'Noortje',        gen: 4, photo: 'katten/noortje.jpeg',       birth: '28 sep 2015' },
  { id: 'snowy',       name: 'Snowy',          gen: 4, photo: 'katten/snowy.jpeg',         birth: '28 sep 2015' },
  { id: 'flynnflo',    name: 'Flynn & Flo',    gen: 5, photo: 'katten/kitties.jpg',        birth: '03 feb 2022' },
  { id: 'kleintje',    name: 'Kleintje',       gen: 5, photo: 'katten/kleintje.jpg',       birth: '21 aug 2018' },
  { id: 'charcoal',    name: 'Charcoal',       gen: 5, photo: 'katten/charcoal.jpg',       birth: '21 aug 2018' },
  { id: 'copper',      name: 'Copper',         gen: 5, photo: 'katten/copper.jpg',         birth: '21 aug 2018' },
  { id: 'pip',         name: 'Pip',            gen: 5, photo: 'katten/pip.jpg',            birth: '21 aug 2018' },
  { id: 'roodje',      name: 'Roodje',         gen: 5, photo: 'katten/roodje.jpg',         birth: '21 aug 2018' },
  { id: 'grijsje',     name: 'Grijsje',        gen: 5, photo: 'katten/grijsje.jpg',        birth: '21 aug 2018' },
  { id: 'bruintje',    name: 'Bruintje',       gen: 5, photo: 'katten/bruintje.jpg',       birth: '21 aug 2018' },
  { id: '1',    name: '1',    gen: 5, photo: null, birth: null },
  { id: '2',    name: '2',    gen: 5, photo: null, birth: null },
  { id: '3',    name: '3',    gen: 5, photo: null, birth: null },
  { id: '4',    name: '4',    gen: 5, photo: null, birth: null },
  { id: '5',    name: '5',    gen: 5, photo: null, birth: null },
];

export const links = [
  { source: 'ginny',      target: 'ruby' },
  { source: 'safira',     target: 'roosje' },
  { source: 'safira',     target: 'midnight' },
  { source: 'safira',     target: 'sparkle' },
  { source: 'safira',     target: 'lieffie' },
  { source: 'safira',     target: 'lily' },
  { source: 'safira',     target: 'royke' },
  { source: 'lily',       target: 'speedy' },
  { source: 'lily',       target: 'piraatje' },
  { source: 'lily',       target: 'bloesempje' },
  { source: 'lily',       target: 'schatje' },
  { source: 'lily',       target: 'lillifee' },
  { source: 'speedy',     target: 'flip' },
  { source: 'speedy',     target: 'fjoepie' },
  { source: 'speedy',     target: 'spilly' },
  { source: 'speedy',     target: 'noodle' },
  { source: 'speedy',     target: 'nibbit' },
  { source: 'piraatje',   target: 'streepje' },
  { source: 'piraatje',   target: 'ziva' },
  { source: 'piraatje',   target: 'zara' },
  { source: 'piraatje',   target: 'sunny' },
  { source: 'piraatje',   target: 'sneeuwvlokje' },
  { source: 'piraatje',   target: 'oreo' },
  { source: 'bloesempje', target: 'bambi' },
  { source: 'bloesempje', target: 'shadow' },
  { source: 'bloesempje', target: 'charlie' },
  { source: 'bloesempje', target: 'noortje' },
  { source: 'bloesempje', target: 'snowy' },
  { source: 'ziva',       target: 'kleintje' },
  { source: 'ziva',       target: 'charcoal' },
  { source: 'ziva',       target: 'copper' },
  { source: 'ziva',       target: 'grijsje' },
  { source: 'ziva',       target: 'bruintje' },
  { source: 'ziva',       target: 'pip' },
  { source: 'ziva',       target: 'roodje' },
  { source: 'fjoepie',    target: 'flynnflo' },
  { source: 'zara',       target: '1' },
  { source: 'zara',       target: '2' },
  { source: 'zara',       target: '3' },
  { source: 'zara',       target: '4' },
  { source: 'zara',       target: '5' },
];
